set fish_color_autosuggestion d0d0d0
set fish_color_command 005fd7\x1epurple
set fish_color_comment red
set fish_color_cwd 1c1c1c
set fish_color_cwd_root red
set fish_color_error 870000\x1e\x2d\x2dbold
set fish_color_escape 87afff
set fish_color_history_current 5f5fff
set fish_color_host \x2do\x1ecyan
set fish_color_match 5f5fff
set fish_color_normal 000000
set fish_color_operator 5f5fff
set fish_color_param 000000
set fish_color_quote brown
set fish_color_redirection normal
set fish_color_search_match \x2d\x2dbackground\x3dpurple
set fish_color_status red
set fish_color_user \x2do\x1egreen
set fish_color_valid_path \x2d\x2dunderline
set fish_pager_color_completion normal
set fish_pager_color_description 555\x1eyellow
set fish_pager_color_prefix cyan
set fish_pager_color_progress cyan
